---
title: 病
author: ''
date: '2018-12-11'
slug: ''
categories: []
tags: []
header:
  caption: ''
  image: ''
---

这个冬天注定是难受的，发现自己失去了久坐的能力，坐一个小时就不舒服，就去校医院查，校医院查不出问题，就去北医三院查，等了一个星期做了个CT，结果出来，说可能是肝硬化，如果真是那是真绝望了，但是我没有发现自己有肝硬化的那些早期的症状。北医三院消化科据说是全国Number  one，所以很难有号，明天再打电话试一试吧。

有去了清华长庚医院，医生觉得可能和肝没有问题，建议我们去做核磁共振，看看腰椎有没有什么问题。（这几天腰椎发现没有什么问题，但是颈椎越来越不舒服，真是遇到鬼了，我到底是怎么了！！！）

今天又因为填表的事情被刘老师说了，我显然是非常拒斥干这些事情的，我不觉得这些事情有什么特别有趣的地方，琐碎，浪费时间，我干活那种马马虎虎地态度她显然很生气吧。身处在这样的环境中其实如何自处真是一个很大的问题，自己的个性显然不愿意甘当干这些琐碎的事情的机器，但是显然你不可能完全拒斥干这些事情，撕破脸显然是一件非常不理智的事情。在这把年纪居然还有这些问题，真是对自己感到无奈。能在这种微妙中保持一种平衡是一件非常困难的事情。能做到显然是非常之人。

有太多的事情要求到她，不可能和她翻脸，代价太大了。我没有这样的底气和她硬碰硬，看来只能默默地忍了。希望能早点离开这里。人生到处都是虎穴，到哪里都得不到自己想要的自由，除非自己当老大，可以不在乎任何人，可惜，自己也没有那个本事。做一个聪明的人，而不是做一个没有任何意义的纯粹自我牺牲的蠢蛋。


模态逻辑的学习就是对自己心性的一个锻炼，从头开始，学好一个东西。这并不是一件坏事，这是一件很好的学习机会。  12/17/2018

今天看了模态逻辑1.2，都感觉到理解的压力，有很多概念需要花很多时间去理解。每一个领域都是一个巨大的坑呀，12/18/2018

中国的学术界就是这样的：老人欺负年轻人，有权势的人压榨没有权势的人，所以才有而今这个畸形生长的状况。 真正感到哲学的路难走是来了清华之后，刘老师其实内心是个冷血的人，把人当牛马使唤，她才不在乎别人怎么样，她只在乎自己的目标有没有达到。这个时代的弄潮儿是像她这样的人，
12/19/2018

近期阅读的文章：

* Actual causation: what is the use?
* counterfactual reasoning 
* causality in thought
* a modification of Halpern-Pearl definition 


